# P = Player
# X = Ground tile
# x = Sky tile
# o = Coin

TILE_SIZE = 64

level_1 = [
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '                                                                                                                                                                                                                                                                                                                                                                                                                                ',
    '       P  o                                                                                                                                                                                                                                                                                                                                                                                                                     ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX']

maps = {
    'level_1': level_1
}
